---
- name: Deploy to Kubernetes Test Environment
  hosts: testnodes
  become: yes
  tasks:
    - name: Copy test deployment manifest to remote node
      copy:
        src: ../../kdeploy-test.yaml
        dest: /home/devopsadmin/kdeploy-test.yaml
        mode: '0644'

    - name: Apply Kubernetes manifests to test namespace
      command: kubectl apply -f /home/devopsadmin/kdeploy-test.yaml

