- name: Deploy to Kubernetes Test Environment
  hosts: testnodes
  become: yes
  tasks:
    - name: Apply Kubernetes manifests to test namespace
      shell: kubectl apply -f /home/devopsadmin/kdeploy-test.yaml
