- hosts: kube-master
  tasks:
    - name: Verify pods in test namespace
      ansible.builtin.shell: kubectl get pods -n test -o jsonpath='{.items[*].status.phase}'
      register: pod_status

    - name: Fail if pods not running
      ansible.builtin.fail:
        msg: "Pods not running: {{ pod_status.stdout }}"
      when: "'Running' not in pod_status.stdout"
